- name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: demo-app
        image: europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/demo-app/demo-app-image:${{ github.sha }}
        region: europe-central2
        # TA LINIA JEST KLUCZOWA:
        service_account: github-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
        flags: '--port=8088 --allow-unauthenticated'
